### ISSUE TITLE
user visible DetachedPackageException

### ISSUE THREAD

**Issue by tvo** [tvo/rapid#12]
When doing `rapid pin 's44:latest mutator'`, I get this exception:

```
Traceback (most recent call last):
  File "/usr/bin/rapid", line 163, in <module>
    main()
  File "/usr/bin/rapid", line 119, in main
    pin(req_arg())
  File "/usr/lib/python2.6/site-packages/rapid/main.py", line 120, in pin
    install_single(rapid.packages[t])
  File "/usr/lib/python2.6/site-packages/rapid/main.py", line 143, in install_single
    install_single(d, True)
  File "/usr/lib/python2.6/site-packages/rapid/main.py", line 146, in install_single
    p.install(ProgressBar())
  File "/usr/lib/python2.6/site-packages/rapid/rapid.py", line 536, in install
    self.download_files(self.missing_files, progress)
  File "/usr/lib/python2.6/site-packages/rapid/rapid.py", line 520, in missing_files
    return filter(lambda f: not f.available, self.files)
  File "/usr/lib/python2.6/site-packages/rapid/rapid.py", line 428, in files
    self.download()
  File "/usr/lib/python2.6/site-packages/rapid/rapid.py", line 416, in download
    raise DetachedPackageException()
rapid.rapid.DetachedPackageException
```

It's because the package has been removed from the server.

There should be a nicer error message for this. (Package is no longer available blabla..)

**Comment by tvo** [comment]
Really need to fix this.. I just hit it again, personally :-)

**Comment by hoijui** [comment]
same here. it does only show `Installing: Complete Annihilation PZK test-149` and then crashes.
so i guess it happens because of this package, but it does not show the package-name, so i had to list pinned packages. guess a regular user would have big problems with that.
i guess Licho & co removed all CA stuff from the server.
