### ISSUE TITLE
rapid is broken

### ISSUE THREAD

**Issue by abma** [tvo/rapid#41]
D:\spring92-testing>rapid\rapid.exe pin evo:stable
Using data directory: D:\spring92-testing\
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
  File "bin/rapid", line 7, in <module>
  File "Z:\python\rapid\rapid\ui\text\main.py", line 131, in main
  File "Z:\python\rapid\rapid\main.py", line 40, in pin
  File "Z:\python\rapid\rapid\rapid.py", line 318, in tags
  File "Z:\python\rapid\rapid\rapid.py", line 226, in tags
  File "Z:\python\rapid\rapid\rapid.py", line 184, in load
  File "Z:\python\rapid\rapid\rapid.py", line 137, in **iter**
  File "Z:\python\rapid\rapid\rapid.py", line 124, in list
  File "Z:\python\rapid\rapid\rapid.py", line 111, in load
  File "Z:\python\rapid\rapid\util\downloader.py", line 87, in conditional_get_r
equest
  File "C:\Python26\lib\urllib2.py", line 383, in open
    response = self._open(req, data)
  File "C:\Python26\lib\urllib2.py", line 401, in _open
    '_open', req)
  File "C:\Python26\lib\urllib2.py", line 361, in _call_chain
    result = func(*args)
  File "C:\Python26\lib\urllib2.py", line 1130, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python26\lib\urllib2.py", line 1105, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

see http://springrts.com/mantis/view.php?id=3472

not sure why, i guess because caspring.org doesn't exist any more, maybe already fixed by https://github.com/tvo/rapid/commit/ffcf89133e6d73d3e5fe1cbd0545d77eb7a65922

-> win32 build needs to be created

**Comment by ScarylePoo** [comment]
I haz qq _sniff_

**Comment by tvo** [comment]
I'll see if I can take a look tonight PST.

**Comment by abma** [comment]
caspring.org is down... -> repos.gz can't be downloaded

this is already fixed in current master (https://github.com/tvo/rapid/commit/ffcf89133e6d73d3e5fe1cbd0545d77eb7a65922) branch, but the win32 "build" needs a new release. (not 100% sure, but it really looks like this is the cause)
